//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.XsdConvert.genericRailML
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eAnnotation", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class EAnnotation : genericRailML.TAnnotation
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<genericRailML.TAnnotationText> _text;
        
        /// <summary>
        /// <para>could be the instructions to drivers, used by an AVL (de:RBL) system, or the message on printouts</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("text", Order=0)]
        public System.Collections.ObjectModel.Collection<genericRailML.TAnnotationText> Text
        {
            get
            {
                return this._text;
            }
            private set
            {
                this._text = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="EAnnotation" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EAnnotation" /> class.</para>
        /// </summary>
        public EAnnotation()
        {
            this._text = new System.Collections.ObjectModel.Collection<genericRailML.TAnnotationText>();
        }
    }
}
