//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.XsdConvert.genericRailML
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eOcpTT", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class EOcpTT : genericRailML.TOcpTT
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<EArrivalDepartureTimes> _times;
        
        [System.Xml.Serialization.XmlElementAttribute("times", Order=0)]
        public System.Collections.ObjectModel.Collection<EArrivalDepartureTimes> Times
        {
            get
            {
                return this._times;
            }
            private set
            {
                this._times = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Times-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Times collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public bool TimesSpecified
        {
            get
            {
                return (this.Times.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="EOcpTT" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EOcpTT" /> class.</para>
        /// </summary>
        public EOcpTT()
        {
            this._times = new System.Collections.ObjectModel.Collection<EArrivalDepartureTimes>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("connections", Order=1)]
        public EConnectionsTT Connections { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("statistics", Order=2)]
        public EStatistics Statistics { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sectionTT", Order=3)]
        public ESectionTT SectionTT { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stopDescription", Order=4)]
        public EStopDescription StopDescription { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return this._any;
            }
            private set
            {
                this._any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Any-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
