//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.XsdConvert.genericRailML
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eTransformer", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class ETransformer : genericRailML.TTransformer
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<genericRailML.TWinding> _winding;
        
        /// <summary>
        /// <para>nominal values of each transformer winding</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("winding", Order=0)]
        public System.Collections.ObjectModel.Collection<genericRailML.TWinding> Winding
        {
            get
            {
                return this._winding;
            }
            private set
            {
                this._winding = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Winding-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Winding collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public bool WindingSpecified
        {
            get
            {
                return (this.Winding.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ETransformer" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ETransformer" /> class.</para>
        /// </summary>
        public ETransformer()
        {
            this._winding = new System.Collections.ObjectModel.Collection<genericRailML.TWinding>();
        }
        
        /// <summary>
        /// <para>transformer efficiency vs. speed</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("efficiency", Order=1)]
        public genericRailML.TEfficiencyCurve Efficiency { get; set; }
    }
}
