//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.XsdConvert.genericRailML
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    internal partial interface IABasicBrakeAttributes : IAMinBasicBrakeAttributes
    {
        
        /// <summary>
        /// <para>brake mass for normal brake operations of none-automatic brakes</para>
        /// <para>generic type for weight/load values measured in ton</para>
        /// </summary>
        System.Nullable<decimal> RegularBrakeMass
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>brake mass for emergency brake operations, differs from regular brake mass depending on auxiliary brakes</para>
        /// <para>generic type for weight/load values measured in ton</para>
        /// </summary>
        System.Nullable<decimal> EmergencyBrakeMass
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>alternative specification of maximum possible momentary deceleration</para>
        /// <para>generic type for acceleration values measured in meter per square second</para>
        /// </summary>
        System.Nullable<decimal> MaxDeceleration
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>alternative specification of effective mean deceleration of a whole brake operation</para>
        /// <para>generic type for acceleration values measured in meter per square second</para>
        /// </summary>
        System.Nullable<decimal> MeanDeceleration
        {
            get;
            set;
        }
    }
}
