CREATE TABLE [dbo].[ETrackElements]
(
	--From MergedXSDs XSD
	--From 'genericRailML' Namespace
	[ETrackElementsId]			BIGINT			NOT NULL,
	[SpeedChanges]				BIGINT			NOT NULL,
	[GradientChanges]			BIGINT			NOT NULL,
	[RadiusChanges]			BIGINT			NOT NULL,
	[Tunnels]					BIGINT			NOT NULL,
	[Bridges]					BIGINT			NOT NULL,
	[LevelCrossings]			BIGINT			NOT NULL,
	[OwnerChanges]				BIGINT			NOT NULL,
	[OperationModeChanges]		BIGINT			NOT NULL,
	[TrainProtectionChanges]	BIGINT			NOT NULL,
	[ElectrificationChanges]	BIGINT			NOT NULL,
	[PowerTransmissionChanges]	BIGINT			NOT NULL,
	[AxleWeightChanges]		BIGINT			NOT NULL,
	[GaugeChanges]				BIGINT			NOT NULL,
	[ClearanceGaugeChanges]	BIGINT			NOT NULL,
	[GeoMappings]				BIGINT			NOT NULL,
	[TrackConditions]			BIGINT			NOT NULL,
	[PlatformEdges]			BIGINT			NOT NULL,
	[ServiceSections]			BIGINT			NOT NULL,
	[Any]						VARCHAR(MAX)		NOT NULL,

	CONSTRAINT [PK_ETrackElementsId] PRIMARY KEY CLUSTERED ([ETrackElementsId] ASC),
	CONSTRAINT [FK_ETrackElements_ESpeedChanges] FOREIGN KEY ([SpeedChanges]) REFERENCES [dbo].[ESpeedChanges] ([ESpeedChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EGradientChanges] FOREIGN KEY ([GradientChanges]) REFERENCES [dbo].[EGradientChanges] ([EGradientChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_ERadiusChanges] FOREIGN KEY ([RadiusChanges]) REFERENCES [dbo].[ERadiusChanges] ([ERadiusChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_ETunnels] FOREIGN KEY ([Tunnels]) REFERENCES [dbo].[ETunnels] ([ETunnelsId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EBridges] FOREIGN KEY ([Bridges]) REFERENCES [dbo].[EBridges] ([EBridgesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_ELevelCrossings] FOREIGN KEY ([LevelCrossings]) REFERENCES [dbo].[ELevelCrossings] ([ELevelCrossingsId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EOwnerChanges] FOREIGN KEY ([OwnerChanges]) REFERENCES [dbo].[EOwnerChanges] ([EOwnerChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EOperationModeChanges] FOREIGN KEY ([OperationModeChanges]) REFERENCES [dbo].[EOperationModeChanges] ([EOperationModeChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_ETrainProtectionChanges] FOREIGN KEY ([TrainProtectionChanges]) REFERENCES [dbo].[ETrainProtectionChanges] ([ETrainProtectionChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EElectrificationChanges] FOREIGN KEY ([ElectrificationChanges]) REFERENCES [dbo].[EElectrificationChanges] ([EElectrificationChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EPowerTransmissionChanges] FOREIGN KEY ([PowerTransmissionChanges]) REFERENCES [dbo].[EPowerTransmissionChanges] ([EPowerTransmissionChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EAxleWeightChanges] FOREIGN KEY ([AxleWeightChanges]) REFERENCES [dbo].[EAxleWeightChanges] ([EAxleWeightChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EGaugeChanges] FOREIGN KEY ([GaugeChanges]) REFERENCES [dbo].[EGaugeChanges] ([EGaugeChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EClearanceGaugeChanges] FOREIGN KEY ([ClearanceGaugeChanges]) REFERENCES [dbo].[EClearanceGaugeChanges] ([EClearanceGaugeChangesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EGeoMappings] FOREIGN KEY ([GeoMappings]) REFERENCES [dbo].[EGeoMappings] ([EGeoMappingsId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_ETrackConditions] FOREIGN KEY ([TrackConditions]) REFERENCES [dbo].[ETrackConditions] ([ETrackConditionsId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EPlatformEdges] FOREIGN KEY ([PlatformEdges]) REFERENCES [dbo].[EPlatformEdges] ([EPlatformEdgesId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_ETrackElements_EServiceSections] FOREIGN KEY ([ServiceSections]) REFERENCES [dbo].[EServiceSections] ([EServiceSectionsId]) --ON UPDATE CASCADE, ON DELETE CASCADE,
);
