CREATE TABLE [dbo].[TPropulsion]
(
	--From MergedXSDs XSD
	--From 'genericRailML' Namespace
	[TPropulsionId]								SMALLINT			NOT NULL,
	[VoltageValue]									DECIMAL(18, 6)	NOT NULL,
	[VoltageValueSpecified]						BIT				NOT NULL,
	[FrequencyValue]								DECIMAL(18, 6)	NOT NULL,
	[FrequencyValueSpecified]						BIT				NOT NULL,
	[Power]										DECIMAL(18, 6)	NOT NULL,
	[PowerType]									NVARCHAR(MAX)	NOT NULL,
	[Transmission]									NVARCHAR(MAX)	NOT NULL,
	[ControlType]									NVARCHAR(MAX)	NOT NULL,
	[MaxTractEffortValue]							DECIMAL(18, 6)	NOT NULL,
	[MaxTractEffortValueSpecified]					BIT				NOT NULL,
	[RotationMassFactorValue]						DECIMAL(18, 6)	NOT NULL,
	[RotationMassFactorValueSpecified]				BIT				NOT NULL,
	[AdditionalRotationMassValue]					DECIMAL(18, 6)	NOT NULL,
	[AdditionalRotationMassValueSpecified]			BIT				NOT NULL,
	[RackTractionValue]							BIT				NOT NULL,
	[RackTractionValueSpecified]					BIT				NOT NULL,
	[RemoteControlValue]							BIT				NOT NULL,
	[RemoteControlValueSpecified]					BIT				NOT NULL,
	[NumberNotches]								NVARCHAR(MAX)	NOT NULL,
	[WheelDiameterValue]							DECIMAL(18, 6)	NOT NULL,
	[WheelDiameterValueSpecified]					BIT				NOT NULL,
	[MaxBrakeEffortValue]							DECIMAL(18, 6)	NOT NULL,
	[MaxBrakeEffortValueSpecified]					BIT				NOT NULL,
	[MaxBrakePowerValue]							DECIMAL(18, 6)	NOT NULL,
	[MaxBrakePowerValueSpecified]					BIT				NOT NULL,
	[TotalTractEfficiencyValue]					DECIMAL(18, 6)	NOT NULL,
	[TotalTractEfficiencyValueSpecified]			BIT				NOT NULL,
	[TotalBrakeEfficiencyValue]					DECIMAL(18, 6)	NOT NULL,
	[TotalBrakeEfficiencyValueSpecified]			BIT				NOT NULL,
	[TractionOffUndervoltageThresholdValue]		DECIMAL(18, 6)	NOT NULL,
	[TractionOffUndervoltageThresholdValueSpecified]	BIT				NOT NULL,
	[ZeroSpeedCurrentLimitationValue]				DECIMAL(18, 6)	NOT NULL,
	[ZeroSpeedCurrentLimitationValueSpecified]		BIT				NOT NULL,
	[MaxRegenerativeVoltageValue]					DECIMAL(18, 6)	NOT NULL,
	[MaxRegenerativeVoltageValueSpecified]			BIT				NOT NULL,
	[SpeedRangeValue]								TINYINT			NOT NULL,
	[SpeedRangeValueSpecified]						BIT				NOT NULL,
	[ForwardSpeedValue]							DECIMAL(18, 6)	NOT NULL,
	[ForwardSpeedValueSpecified]					BIT				NOT NULL,
	[ReverseSpeedValue]							DECIMAL(18, 6)	NOT NULL,
	[ReverseSpeedValueSpecified]					BIT				NOT NULL,
	[ActivationStandstillValue]					BIT				NOT NULL,
	[ActivationStandstillValueSpecified]			BIT				NOT NULL,

	CONSTRAINT [PK_TPropulsionId] PRIMARY KEY CLUSTERED ([TPropulsionId] ASC),
	CONSTRAINT [FK_TPropulsion_TSpeedRangeType] FOREIGN KEY ([SpeedRangeValue]) REFERENCES [dbo].[TSpeedRangeType] ([TSpeedRangeTypeId]) --ON UPDATE CASCADE, ON DELETE CASCADE,
);
