CREATE TABLE [dbo].[TSignal]
(
	--From MergedXSDs XSD
	--From 'genericRailML' Namespace
	[TSignalId]							SMALLINT			NOT NULL,
	[Speed]								SMALLINT			NOT NULL,
	[Etcs]									SMALLINT			NOT NULL,
	[LevelCrossing]						SMALLINT			NOT NULL,
	[TrainRadio]							SMALLINT			NOT NULL,
	[Catenary]								SMALLINT			NOT NULL,
	[Line]									SMALLINT			NOT NULL,
	[Milepost]								SMALLINT			NOT NULL,
	[Braking]								SMALLINT			NOT NULL,
	[TrainProtectionElementGroupRef]		BIGINT			NOT NULL,
	[BaliseGroupRef]						BIGINT			NOT NULL,
	[SightValue]							DECIMAL(18, 6)	NOT NULL,
	[SightValueSpecified]					BIT				NOT NULL,
	[Type]									NVARCHAR(MAX)	NOT NULL,
	[Function]								NVARCHAR(MAX)	NOT NULL,
	[SigSystem]							NVARCHAR(MAX)	NOT NULL,
	[SwitchableValue]						BIT				NOT NULL,
	[SwitchableValueSpecified]				BIT				NOT NULL,
	[MaskableRouteValue]					BIT				NOT NULL,
	[MaskableRouteValueSpecified]			BIT				NOT NULL,
	[MaskableATCValue]						BIT				NOT NULL,
	[MaskableATCValueSpecified]			BIT				NOT NULL,
	[Virtual]								BIT				NOT NULL,
	[SignalBoxOcpRef]						NVARCHAR(MAX)	NOT NULL,
	[StationOcpRef]						NVARCHAR(MAX)	NOT NULL,
	[DistNearestDangerPointValue]			DECIMAL(18, 6)	NOT NULL,
	[DistNearestDangerPointValueSpecified]	BIT				NOT NULL,
	[TrackDistValue]						DECIMAL(18, 6)	NOT NULL,
	[TrackDistValueSpecified]				BIT				NOT NULL,
	[HeightValue]							DECIMAL(18, 6)	NOT NULL,
	[HeightValueSpecified]					BIT				NOT NULL,
	[OcpStationRef]						NVARCHAR(MAX)	NOT NULL,
	[ControllerRef]						NVARCHAR(MAX)	NOT NULL,

	CONSTRAINT [PK_TSignalId] PRIMARY KEY CLUSTERED ([TSignalId] ASC),
	CONSTRAINT [FK_TSignal_TElementWithReference1] FOREIGN KEY ([TrainProtectionElementGroupRef]) REFERENCES [dbo].[TElementWithReference] ([TElementWithReferenceId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_TSignal_TElementWithReference2] FOREIGN KEY ([BaliseGroupRef]) REFERENCES [dbo].[TElementWithReference] ([TElementWithReferenceId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_TSignal_TSignalSpeed] FOREIGN KEY ([Speed]) REFERENCES [dbo].[TSignalSpeed] ([TSignalSpeedId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_TSignal_TSignalEtcs] FOREIGN KEY ([Etcs]) REFERENCES [dbo].[TSignalEtcs] ([TSignalEtcsId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_TSignal_TSignalLevelCrossing] FOREIGN KEY ([LevelCrossing]) REFERENCES [dbo].[TSignalLevelCrossing] ([TSignalLevelCrossingId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_TSignal_TSignalTrainRadio] FOREIGN KEY ([TrainRadio]) REFERENCES [dbo].[TSignalTrainRadio] ([TSignalTrainRadioId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_TSignal_TSignalCatenary] FOREIGN KEY ([Catenary]) REFERENCES [dbo].[TSignalCatenary] ([TSignalCatenaryId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_TSignal_TSignalLine] FOREIGN KEY ([Line]) REFERENCES [dbo].[TSignalLine] ([TSignalLineId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_TSignal_TSignalMilepost] FOREIGN KEY ([Milepost]) REFERENCES [dbo].[TSignalMilepost] ([TSignalMilepostId]), --ON UPDATE CASCADE, ON DELETE CASCADE,
	CONSTRAINT [FK_TSignal_TSignalBraking] FOREIGN KEY ([Braking]) REFERENCES [dbo].[TSignalBraking] ([TSignalBrakingId]) --ON UPDATE CASCADE, ON DELETE CASCADE,
);
