//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("eInfraAttrGroupRefs", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class EInfraAttrGroupRefs
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der diese Entität eindeutig identifiziert, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value uniquely identifying this entity.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [KeyAttribute()]
        public long Id { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<genericRailML.TElementWithReference> _infraAttrGroupRef;
        
        /// <summary>
        /// <para>sub-element for a reference to an infraAttributes instance</para>
        /// </summary>
        [XmlElementAttribute("infraAttrGroupRef", Order=0)]
        public Collection<genericRailML.TElementWithReference> InfraAttrGroupRef
        {
            get
            {
                return this._infraAttrGroupRef;
            }
            private set
            {
                this._infraAttrGroupRef = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die InfraAttrGroupRef-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the InfraAttrGroupRef collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        public bool InfraAttrGroupRefSpecified
        {
            get
            {
                return (this.InfraAttrGroupRef.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="EInfraAttrGroupRefs" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EInfraAttrGroupRefs" /> class.</para>
        /// </summary>
        public EInfraAttrGroupRefs()
        {
            this._infraAttrGroupRef = new Collection<genericRailML.TElementWithReference>();
        }
    }
}
