//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("eInfrastructureVisualization", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class EInfrastructureVisualization : genericRailML.TInfrastructureVisualization
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ELineVis> _lineVis;
        
        /// <summary>
        /// <para>visualization of a railway line</para>
        /// </summary>
        [XmlElementAttribute("lineVis", Order=0)]
        public Collection<ELineVis> LineVis
        {
            get
            {
                return this._lineVis;
            }
            private set
            {
                this._lineVis = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die LineVis-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the LineVis collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        public bool LineVisSpecified
        {
            get
            {
                return (this.LineVis.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="EInfrastructureVisualization" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EInfrastructureVisualization" /> class.</para>
        /// </summary>
        public EInfrastructureVisualization()
        {
            this._lineVis = new Collection<ELineVis>();
            this._ocpVis = new Collection<EOcpVis>();
        }
        
        [XmlIgnoreAttribute()]
        private Collection<EOcpVis> _ocpVis;
        
        /// <summary>
        /// <para>visualization of an OCP</para>
        /// </summary>
        [XmlElementAttribute("ocpVis", Order=1)]
        public Collection<EOcpVis> OcpVis
        {
            get
            {
                return this._ocpVis;
            }
            private set
            {
                this._ocpVis = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die OcpVis-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the OcpVis collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        public bool OcpVisSpecified
        {
            get
            {
                return (this.OcpVis.Count != 0);
            }
        }
    }
}
