//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.XsdConvert.genericRailML
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eTrackNode", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ETrackBegin))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ETrackEnd))]
    internal partial class ETrackNode : genericRailML.TTrackNode
    {
        
        [System.Xml.Serialization.XmlElementAttribute("connection", Order=0)]
        public genericRailML.TConnectionData Connection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("bufferStop", Order=1)]
        public genericRailML.TBufferStop BufferStop { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("openEnd", Order=2)]
        public genericRailML.TOpenEnd OpenEnd { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("macroscopicNode", Order=3)]
        public genericRailML.TMacroscopicNode MacroscopicNode { get; set; }
    }
}
