//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    internal partial interface IAVehicleIdentification
    {
        
        /// <summary>
        /// <para>the UIC identification number with 12 digits</para>
        /// <para>an identification string consisting of exactly twelve digits, e.g. UIC ident numbers</para>
        /// </summary>
        string UicIdentNumber
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>code for the registered country (one to three letters)</para>
        /// <para xml:lang="en">Pattern: \w{1,3}.</para>
        /// </summary>
        [RegularExpressionAttribute("\\w{1,3}")]
        string CountryCode
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>code for the vehicle ownwer (one to five letters)</para>
        /// <para xml:lang="en">Pattern: \w{1,5}.</para>
        /// </summary>
        [RegularExpressionAttribute("\\w{1,5}")]
        string VehicleKeeperMarking
        {
            get;
            set;
        }
    }
}
