//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("tCirculation", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class TCirculation : IACirculation, genericRailML.IAnyAttribute
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der diese Entität eindeutig identifiziert, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value uniquely identifying this entity.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [KeyAttribute()]
        public long Id { get; set; }
        
        /// <summary>
        /// <para>an XML-side constrained reference to one xs:ID value, acts across an XML file including its outsourced components (xi:include mechanism)</para>
        /// </summary>
        [XmlAttributeAttribute("blockRef")]
        public string BlockRef { get; set; }
        
        /// <summary>
        /// <para>if not defined: operatingPeriodRef must be defined</para>
        /// </summary>
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [NotMappedAttribute()]
        [XmlAttributeAttribute("startDate", DataType="date")]
        public System.DateTime StartDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die StartDate-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the StartDate property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool StartDateValueSpecified { get; set; }
        
        /// <summary>
        /// <para>if not defined: operatingPeriodRef must be defined</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                if (this.StartDateValueSpecified)
                {
                    return this.StartDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.StartDateValue = value.GetValueOrDefault();
                this.StartDateValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>if not defined: as operatingPeriod or open end</para>
        /// </summary>
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [NotMappedAttribute()]
        [XmlAttributeAttribute("endDate", DataType="date")]
        public System.DateTime EndDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die EndDate-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EndDate property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool EndDateValueSpecified { get; set; }
        
        /// <summary>
        /// <para>if not defined: as operatingPeriod or open end</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                if (this.EndDateValueSpecified)
                {
                    return this.EndDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EndDateValue = value.GetValueOrDefault();
                this.EndDateValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>if not defined: daily from startDate to endDate</para>
        /// <para>an XML-side constrained reference to one xs:ID value, acts across an XML file including its outsourced components (xi:include mechanism)</para>
        /// </summary>
        [XmlAttributeAttribute("operatingPeriodRef")]
        public string OperatingPeriodRef { get; set; }
        
        /// <summary>
        /// <para>for abstract circulations without start/endDate</para>
        /// <para>generic type for counters (e.g. number of equipment), allowing zero</para>
        /// </summary>
        [XmlAttributeAttribute("repeatCount")]
        public string RepeatCount { get; set; }
        
        /// <summary>
        /// <para>indicating the right vehicle number (de: Fahrzeugnummer) within the circulations</para>
        /// <para>generic type for counters (e.g. number of equipment), allowing zero</para>
        /// </summary>
        [XmlAttributeAttribute("vehicleCounter")]
        public string VehicleCounter { get; set; }
        
        /// <summary>
        /// <para>indicating the right vehicle group number (de: Gruppennummer) within the circulations</para>
        /// <para>generic type for counters (e.g. number of equipment), allowing zero</para>
        /// </summary>
        [XmlAttributeAttribute("vehicleGroupCounter")]
        public string VehicleGroupCounter { get; set; }
        
        /// <summary>
        /// <para>an XML-side constrained reference to one xs:ID value, acts across an XML file including its outsourced components (xi:include mechanism)</para>
        /// </summary>
        [XmlAttributeAttribute("nextBlockRef")]
        public string NextBlockRef { get; set; }
        
        /// <summary>
        /// <para>there has to be an information to which operation day of the next block the current block should be linked to. A vehicle can make a standstill for several days but the defined next block inside of the circulation may run every day</para>
        /// <para>an XML-side constrained reference to one xs:ID value, acts across an XML file including its outsourced components (xi:include mechanism)</para>
        /// </summary>
        [XmlAttributeAttribute("nextOperatingPeriodRef")]
        public string NextOperatingPeriodRef { get; set; }
    }
}
