//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.XsdConvert.genericRailML
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tOcpTTType", Namespace="https://www.railml.org/schemas/2018")]
    internal enum TOcpTTType
    {
        
        /// <summary>
        /// <para>indicates that the train is going to stop at this ocp</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("stop")]
        Stop,
        
        /// <summary>
        /// <para>indicates that the train is NOT going to stop at this ocp</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("pass")]
        Pass,
        
        /// <summary>
        /// <para>DEPRECATED: possible for the first ocp, if train part begins at this ocp and is not part of a longer train path</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("begin")]
        Begin,
        
        /// <summary>
        /// <para>DEPRECATED: possible for the last ocp, if train part ends at this ocp and is not part of a longer train path</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("end")]
        End,
    }
}
