//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("tPlacedElement", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlIncludeAttribute(typeof(genericRailML.ECrossing))]
    [XmlIncludeAttribute(typeof(genericRailML.ELevelCrossing))]
    [XmlIncludeAttribute(typeof(genericRailML.ESwitch))]
    [XmlIncludeAttribute(typeof(TAxleWeightChange))]
    [XmlIncludeAttribute(typeof(TBalise))]
    [XmlIncludeAttribute(typeof(TBorder))]
    [XmlIncludeAttribute(typeof(TClearanceGaugeChange))]
    [XmlIncludeAttribute(typeof(TCommonSwitchAndCrossingData))]
    [XmlIncludeAttribute(typeof(TCrossing))]
    [XmlIncludeAttribute(typeof(TCrossSection))]
    [XmlIncludeAttribute(typeof(TDelimitedOrientedElement))]
    [XmlIncludeAttribute(typeof(TDerailer))]
    [XmlIncludeAttribute(typeof(TElectrificationChange))]
    [XmlIncludeAttribute(typeof(TGaugeChange))]
    [XmlIncludeAttribute(typeof(TGradientChange))]
    [XmlIncludeAttribute(typeof(TLevelCrossing))]
    [XmlIncludeAttribute(typeof(TLock))]
    [XmlIncludeAttribute(typeof(TOperationModeChange))]
    [XmlIncludeAttribute(typeof(TOrientedElement))]
    [XmlIncludeAttribute(typeof(TOwnerChange))]
    [XmlIncludeAttribute(typeof(TPowerTransmissionChange))]
    [XmlIncludeAttribute(typeof(TRadiusChange))]
    [XmlIncludeAttribute(typeof(TRuleCodeElement))]
    [XmlIncludeAttribute(typeof(TSignal))]
    [XmlIncludeAttribute(typeof(TSpeedChange))]
    [XmlIncludeAttribute(typeof(TStopPost))]
    [XmlIncludeAttribute(typeof(TStrictOrientedElement))]
    [XmlIncludeAttribute(typeof(TSwitch))]
    [XmlIncludeAttribute(typeof(TTrackCircuitBorder))]
    [XmlIncludeAttribute(typeof(TTrackCondition))]
    [XmlIncludeAttribute(typeof(TTrainDetector))]
    [XmlIncludeAttribute(typeof(TTrainProtectionChange))]
    [XmlIncludeAttribute(typeof(TTrainProtectionElement))]
    [XmlIncludeAttribute(typeof(TTrainRadioChange))]
    internal partial class TPlacedElement : TBasePlacedElement
    {
        
        /// <summary>
        /// <para>Container to define disabled/enabled pieces of infrastructure.</para>
        /// </summary>
        [XmlElementAttribute("states", Order=0)]
        public TStates States { get; set; }
    }
}
