//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.XsdConvert.genericRailML
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [XmlTypeAttribute("tTrainProtectionElement", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class TTrainProtectionElement : TOrientedElement
    {
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [NotMappedAttribute()]
        [XmlAttributeAttribute("medium")]
        public genericRailML.TTrainProtectionMedium MediumValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Medium-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Medium property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool MediumValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public System.Nullable<genericRailML.TTrainProtectionMedium> Medium
        {
            get
            {
                if (this.MediumValueSpecified)
                {
                    return this.MediumValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MediumValue = value.GetValueOrDefault();
                this.MediumValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>DEPRECATED: use the enumeration parameter trainProtectionSystem instead</para>
        /// </summary>
        [XmlAttributeAttribute("system")]
        public string System { get; set; }
        
        /// <summary>
        /// <para>definition of the national train protection system, which is installed at the track</para>
        /// <para>use value from the separate code definition file 'TrainProtectionSystems.xml'/trainProtectionSystemsAtTrack</para>
        /// </summary>
        [XmlAttributeAttribute("trainProtectionSystem")]
        public string TrainProtectionSystem { get; set; }
        
        [XmlAttributeAttribute("model")]
        public string Model { get; set; }
    }
}
