//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("tTunnel", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlIncludeAttribute(typeof(genericRailML.ETunnel))]
    internal partial class TTunnel : TDelimitedOrientedElementWithLength
    {
        
        /// <summary>
        /// <para>The area of the tunnel cross section in square meters.</para>
        /// <para>Attention: currently the units given for crossSection in railML is given in metres (tLengthM), but to be understood and used as square metres. This issue will be fixed in a future railML version.</para>
        /// <para>generic type for length values measured in meter</para>
        /// </summary>
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [NotMappedAttribute()]
        [XmlAttributeAttribute("crossSection")]
        public decimal CrossSectionValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die CrossSection-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CrossSection property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool CrossSectionValueSpecified { get; set; }
        
        /// <summary>
        /// <para>The area of the tunnel cross section in square meters.</para>
        /// <para>Attention: currently the units given for crossSection in railML is given in metres (tLengthM), but to be understood and used as square metres. This issue will be fixed in a future railML version.</para>
        /// <para>generic type for length values measured in meter</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public System.Nullable<decimal> CrossSection
        {
            get
            {
                if (this.CrossSectionValueSpecified)
                {
                    return this.CrossSectionValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CrossSectionValue = value.GetValueOrDefault();
                this.CrossSectionValueSpecified = value.HasValue;
            }
        }
        
        [XmlAttributeAttribute("kind")]
        public string Kind { get; set; }
    }
}
