//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eExternalReference", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class EExternalReference
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der diese Entität eindeutig identifiziert, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value uniquely identifying this entity.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public long Id { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tafTapTsiTrainID", Order=0)]
        public ETapTsiTransportOperationalIdentifier TafTapTsiTrainID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("trainNumber", Order=1)]
        public EExternalReferenceTrainNumber TrainNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lineNumber", Order=2)]
        public EExternalReferenceLineNumber LineNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("information", Order=3)]
        public EExternalReferenceInformation Information { get; set; }
    }
}
