//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eInfraAttrGroup", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class EInfraAttrGroup
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der diese Entität eindeutig identifiziert, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value uniquely identifying this entity.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public long Id { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<EInfraAttr> _infraAttributes;
        
        [System.Xml.Serialization.XmlElementAttribute("infraAttributes", Order=0)]
        public System.Collections.ObjectModel.Collection<EInfraAttr> InfraAttributes
        {
            get
            {
                return this._infraAttributes;
            }
            private set
            {
                this._infraAttributes = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die InfraAttributes-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the InfraAttributes collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public bool InfraAttributesSpecified
        {
            get
            {
                return (this.InfraAttributes.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="EInfraAttrGroup" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EInfraAttrGroup" /> class.</para>
        /// </summary>
        public EInfraAttrGroup()
        {
            this._infraAttributes = new System.Collections.ObjectModel.Collection<EInfraAttr>();
        }
    }
}
