//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eInfraAttr", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class EInfraAttr : TElementWithIDAndNameWithoutAny
    {
        
        [System.Xml.Serialization.XmlElementAttribute("owner", Order=0)]
        public TOwner Owner { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("operationMode", Order=1)]
        public TOperationMode OperationMode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("trainProtection", Order=2)]
        public TTrainProtection TrainProtection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("electrification", Order=3)]
        public TElectrification Electrification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("powerTransmission", Order=4)]
        public TPowerTransmission PowerTransmission { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("axleWeight", Order=5)]
        public TAxleWeight AxleWeight { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gauge", Order=6)]
        public TGauge Gauge { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("clearanceGauge", Order=7)]
        public TClearanceGaugeType ClearanceGauge { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("speeds", Order=8)]
        public ESpeeds Speeds { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("epsgCode", Order=9)]
        public TEpsgCode EpsgCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("trainRadio", Order=10)]
        public TTrainRadioAttributes TrainRadio { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("generalInfraAttributes", Order=11)]
        public EGeneralInfraAttributes GeneralInfraAttributes { get; set; }
    }
}
