//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eOcpPropOperational", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class EOcpPropOperational : TOcpPropOperational
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TOcpUptime> _uptime;
        
        [System.Xml.Serialization.XmlElementAttribute("uptime", Order=0)]
        public System.Collections.ObjectModel.Collection<TOcpUptime> Uptime
        {
            get
            {
                return this._uptime;
            }
            private set
            {
                this._uptime = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Uptime-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Uptime collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public bool UptimeSpecified
        {
            get
            {
                return (this.Uptime.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="EOcpPropOperational" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EOcpPropOperational" /> class.</para>
        /// </summary>
        public EOcpPropOperational()
        {
            this._uptime = new System.Collections.ObjectModel.Collection<TOcpUptime>();
        }
    }
}
