//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eVehicleBrake", Namespace="https://www.railml.org/schemas/2018")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class EVehicleBrake : TBasicBrakeType, IAVehicleBrake
    {
        
        /// <summary>
        /// <para>for wagons with "full" / "empty" switch</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("loadSwitch")]
        public TLoadSwitch LoadSwitchValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die LoadSwitch-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the LoadSwitch property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool LoadSwitchValueSpecified { get; set; }
        
        /// <summary>
        /// <para>for wagons with "full" / "empty" switch</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<TLoadSwitch> LoadSwitch
        {
            get
            {
                if (this.LoadSwitchValueSpecified)
                {
                    return this.LoadSwitchValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.LoadSwitchValue = value.GetValueOrDefault();
                this.LoadSwitchValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>automatically regulated brake percentages depending on actual load of vehicle</para>
        /// <para>Brake percentage as value of braking performance in relation to vehicle weight</para>
        /// <para xml:lang="en">Maximum inclusive value: 225.</para>
        /// <para xml:lang="en">Minimum inclusive value: 6.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "6", "225")]
        [System.Xml.Serialization.XmlAttributeAttribute("autoBrakePercentage")]
        public string AutoBrakePercentage { get; set; }
        
        /// <summary>
        /// <para>maximum brake mass of automatic brake</para>
        /// <para>generic type for weight/load values measured in ton</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("maxAutoBrakeMass")]
        public decimal MaxAutoBrakeMassValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die MaxAutoBrakeMass-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MaxAutoBrakeMass property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool MaxAutoBrakeMassValueSpecified { get; set; }
        
        /// <summary>
        /// <para>maximum brake mass of automatic brake</para>
        /// <para>generic type for weight/load values measured in ton</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> MaxAutoBrakeMass
        {
            get
            {
                if (this.MaxAutoBrakeMassValueSpecified)
                {
                    return this.MaxAutoBrakeMassValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MaxAutoBrakeMassValue = value.GetValueOrDefault();
                this.MaxAutoBrakeMassValueSpecified = value.HasValue;
            }
        }
    }
}
