//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    internal partial interface IABlockPartSequence
    {
        
        /// <summary>
        /// <para>generic type for counters (e.g. order number of a vehicle in an formation), starting with '1'</para>
        /// </summary>
        string Sequence
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>defines the day the blockPart starts if the block runs over midnight (even if it is not longer than 24 hours); first day and default value is 0</para>
        /// <para>generic type for counters (e.g. number of equipment), allowing zero</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("0")]
        string DayOffset
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>duration from the beginning of blocking of the resource until start of blockPart</para>
        /// </summary>
        string PreProcessingTime
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>duration from the end of blockPart until the end of blocking of the resource</para>
        /// </summary>
        string PostProcessingTime
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>an XML-side constrained reference to one xs:ID value, acts across an XML file including its outsourced components (xi:include mechanism)</para>
        /// </summary>
        string BasicBlockRef
        {
            get;
            set;
        }
    }
}
