//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    internal partial interface IAGangway
    {
        
        /// <summary>
        /// <para>flag, whether there is a gangway at the front end of the vehicle</para>
        /// </summary>
        bool FrontEnd
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>flag, whether there is a gangway at the rear end of the vehicle</para>
        /// </summary>
        bool RearEnd
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>vertical position of the gangway, valid for both sides</para>
        /// </summary>
        string Position
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>type of design of the gangway</para>
        /// </summary>
        string DesignType
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>height of gangways floor above top of rail</para>
        /// <para>generic type for length values measured in meter</para>
        /// </summary>
        System.Nullable<decimal> FloorLevel
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>height of gangway for passenger use</para>
        /// <para>generic type for length values measured in meter</para>
        /// </summary>
        System.Nullable<decimal> GangwayHeight
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>width of gangway for passenger use</para>
        /// <para>generic type for length values measured in meter</para>
        /// </summary>
        System.Nullable<decimal> GangwayWidth
        {
            get;
            set;
        }
    }
}
