//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    internal partial interface IALoadLimit
    {
        
        /// <summary>
        /// <para>maximum speed allowed with the load limit</para>
        /// <para>generic type for speed/velocity values measured in kilometer per hour</para>
        /// </summary>
        decimal MaxSpeed
        {
            get;
            set;
        }
    }
}
