//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    internal partial interface IAMaintenanceInterval
    {
        
        /// <summary>
        /// <para>maximum number of days for the interval until the task is due</para>
        /// <para>generic type for counters (e.g. number of equipment), allowing zero</para>
        /// </summary>
        string MaximumIntervalDays
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>maximum number of mileage in km for the interval until the task is due</para>
        /// <para>generic type for length values measured in kilometer</para>
        /// </summary>
        System.Nullable<decimal> MaximumIntervalDistance
        {
            get;
            set;
        }
    }
}
