//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
namespace Models.DB
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    internal partial interface IAWinding
    {
        
        /// <summary>
        /// <para>type of transformer winding as descriptive name</para>
        /// <para>system-wide known name of an railway facility (e.g. station, timetable period or vehicle), allowing digits, letters and white space</para>
        /// </summary>
        string AssemblyName
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>nominal voltage of transformer winding (primary side) in Volts</para>
        /// <para>generic type for voltage values measured in volt</para>
        /// </summary>
        System.Nullable<decimal> NominalVoltage
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>nominal current of transformer winding (primary side) in Amps</para>
        /// <para>generic type for electric current values measured in ampere</para>
        /// </summary>
        System.Nullable<decimal> NominalCurrent
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>transformation ratio of transformer winding (primary/secondary voltage)</para>
        /// </summary>
        System.Nullable<decimal> TransformationRatio
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>resistance of primary winding of one transformer in Ohms</para>
        /// <para>generic type for electric resistance values measured in ohm</para>
        /// </summary>
        System.Nullable<decimal> PrimaryResistance
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>resistance of secondary winding of one transformer in Ohms transformed to primary side</para>
        /// <para>generic type for electric resistance values measured in ohm</para>
        /// </summary>
        System.Nullable<decimal> SecondaryResistance
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>leakage inductance of primary winding of one transformer in H</para>
        /// <para>generic type for inductance values measured in henry</para>
        /// </summary>
        System.Nullable<decimal> PrimaryLeakageInductance
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>leakage inductance of secondary winding of one transformer in H transformed to primary side</para>
        /// <para>generic type for inductance values measured in henry</para>
        /// </summary>
        System.Nullable<decimal> SecondaryLeakageInductance
        {
            get;
            set;
        }
    }
}
