CREATE TABLE [dbo].[EOcpsTT]
(
	--From MergedXSDs XSD
	--From 'genericRailML' Namespace
	[EOcpsTTId]	BIGINT		NOT NULL,
	[OcpTT]	SMALLINT		NOT NULL,

	CONSTRAINT [PK_EOcpsTTId] PRIMARY KEY CLUSTERED ([EOcpsTTId] ASC),
	CONSTRAINT [FK_EOcpsTT_EOcpTT] FOREIGN KEY ([OcpTT]) REFERENCES [dbo].[EOcpTT] ([EOcpTTId]) --ON UPDATE CASCADE, ON DELETE CASCADE,
);
