//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("eTractionInverter", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class ETractionInverter : genericRailML.TTractionInverter
    {
        
        /// <summary>
        /// <para>traction inverter efficiency vs. speed</para>
        /// </summary>
        [XmlElementAttribute("efficiency", Order=0)]
        public genericRailML.TEfficiencyCurve Efficiency { get; set; }
        
        /// <summary>
        /// <para>pulse pattern of the traction inverter</para>
        /// </summary>
        [XmlElementAttribute("pulsePattern", Order=1)]
        public EPulsePattern PulsePattern { get; set; }
    }
}
