//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    /// <summary>
    /// <para>data about the car body of a vehicle and its payload</para>
    /// </summary>
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("eWagon", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class EWagon : genericRailML.TWagon
    {
        
        /// <summary>
        /// <para>data for passenger cars</para>
        /// </summary>
        [XmlElementAttribute("passenger", Order=0)]
        public EPassenger Passenger { get; set; }
        
        /// <summary>
        /// <para>data for freight cars</para>
        /// </summary>
        [XmlElementAttribute("goods", Order=1)]
        public EGoods Goods { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<genericRailML.TElectrificationSystem> _auxiliarySupplySystem;
        
        /// <summary>
        /// <para>installed supply systems for auxiliaries in the vehicle</para>
        /// </summary>
        [XmlElementAttribute("auxiliarySupplySystem", Order=2)]
        public Collection<genericRailML.TElectrificationSystem> AuxiliarySupplySystem
        {
            get
            {
                return this._auxiliarySupplySystem;
            }
            private set
            {
                this._auxiliarySupplySystem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die AuxiliarySupplySystem-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the AuxiliarySupplySystem collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        public bool AuxiliarySupplySystemSpecified
        {
            get
            {
                return (this.AuxiliarySupplySystem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="EWagon" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EWagon" /> class.</para>
        /// </summary>
        public EWagon()
        {
            this._auxiliarySupplySystem = new Collection<genericRailML.TElectrificationSystem>();
            this._driversCab = new Collection<genericRailML.TDriversCabType>();
            this._trainClearanceGauge = new Collection<genericRailML.TClearanceGaugeType>();
        }
        
        [XmlIgnoreAttribute()]
        private Collection<genericRailML.TDriversCabType> _driversCab;
        
        /// <summary>
        /// <para>data about each drivers cab of the vehicle</para>
        /// </summary>
        [XmlElementAttribute("driversCab", Order=3)]
        public Collection<genericRailML.TDriversCabType> DriversCab
        {
            get
            {
                return this._driversCab;
            }
            private set
            {
                this._driversCab = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die DriversCab-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the DriversCab collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        public bool DriversCabSpecified
        {
            get
            {
                return (this.DriversCab.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>data about rack traction equipment of the vehicle used for braking only</para>
        /// </summary>
        [XmlElementAttribute("rackTraction", Order=4)]
        public genericRailML.TRackTractionType RackTraction { get; set; }
        
        /// <summary>
        /// <para>data for couplers between wagons</para>
        /// </summary>
        [XmlElementAttribute("couplers", Order=5)]
        public ECouplers Couplers { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<genericRailML.TClearanceGaugeType> _trainClearanceGauge;
        
        /// <summary>
        /// <para>data about all compatible clearance gauges of the vehicle</para>
        /// </summary>
        [XmlElementAttribute("trainClearanceGauge", Order=6)]
        public Collection<genericRailML.TClearanceGaugeType> TrainClearanceGauge
        {
            get
            {
                return this._trainClearanceGauge;
            }
            private set
            {
                this._trainClearanceGauge = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die TrainClearanceGauge-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the TrainClearanceGauge collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        public bool TrainClearanceGaugeSpecified
        {
            get
            {
                return (this.TrainClearanceGauge.Count != 0);
            }
        }
    }
}
