//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    internal partial interface IAResistanceFormula
    {
        
        /// <summary>
        /// <para>coefficent used for calculation of train resistance according formula of Strahl/Sauthoff</para>
        /// <para>generic type for coefficent values measured in newton</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        System.Nullable<decimal> StrahlFactor
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>flag, whether the coefficents of Davies formula are to be considered mass dependent</para>
        /// </summary>
        System.Nullable<bool> DaviesMassDependent
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>constant coefficent A used for calculation of train resistance according formula of Davies</para>
        /// <para>generic type for coefficent values measured in newton</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        System.Nullable<decimal> DaviesFactorA
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>speed dependent coefficent B used for calculation of train resistance according formula of Davies</para>
        /// <para>generic type for coefficent values measured in newton</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        System.Nullable<decimal> DaviesFactorB
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>square speed dependent coefficent C used for calculation of train resistance according formula of Davies</para>
        /// <para>generic type for coefficent values measured in newton</para>
        /// <para xml:lang="en">Total number of digits in fraction: 6.</para>
        /// </summary>
        System.Nullable<decimal> DaviesFactorC
        {
            get;
            set;
        }
    }
}
