//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("tElectrification", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class TElectrification : IAElectrification
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der diese Entität eindeutig identifiziert, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value uniquely identifying this entity.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [KeyAttribute()]
        public long Id { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<TMaxTrainCurrent> _maxTrainCurrent;
        
        /// <summary>
        /// <para>maximum allowed train current</para>
        /// </summary>
        [XmlElementAttribute("maxTrainCurrent", Order=0)]
        public Collection<TMaxTrainCurrent> MaxTrainCurrent
        {
            get
            {
                return this._maxTrainCurrent;
            }
            private set
            {
                this._maxTrainCurrent = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die MaxTrainCurrent-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the MaxTrainCurrent collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        public bool MaxTrainCurrentSpecified
        {
            get
            {
                return (this.MaxTrainCurrent.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TElectrification" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TElectrification" /> class.</para>
        /// </summary>
        public TElectrification()
        {
            this._maxTrainCurrent = new Collection<TMaxTrainCurrent>();
        }
        
        [XmlIgnoreAttribute()]
        private string _type = "none";
        
        [DefaultValueAttribute("none")]
        [XmlAttributeAttribute("type")]
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private decimal _voltage = 0m;
        
        /// <summary>
        /// <para>generic type for voltage values measured in volt</para>
        /// </summary>
        [DefaultValueAttribute(typeof(decimal), "0")]
        [XmlAttributeAttribute("voltage")]
        public decimal Voltage
        {
            get
            {
                return this._voltage;
            }
            set
            {
                this._voltage = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private decimal _frequency = 0m;
        
        /// <summary>
        /// <para>generic type for frequency values measured in hertz</para>
        /// </summary>
        [DefaultValueAttribute(typeof(decimal), "0")]
        [XmlAttributeAttribute("frequency")]
        public decimal Frequency
        {
            get
            {
                return this._frequency;
            }
            set
            {
                this._frequency = value;
            }
        }
    }
}
