//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("tGeoCoord", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class TGeoCoord
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der diese Entität eindeutig identifiziert, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value uniquely identifying this entity.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [KeyAttribute()]
        public long Id { get; set; }
        
        /// <summary>
        /// <para>an coordinate list consisting of two or three coordinates</para>
        /// <para xml:lang="en">Minimum length: 2.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// </summary>
        [MinLengthAttribute(2)]
        [MaxLengthAttribute(3)]
        [XmlAttributeAttribute("coord")]
        public Collection<double> Coord { get; private set; }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="TGeoCoord" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TGeoCoord" /> class.</para>
        /// </summary>
        public TGeoCoord()
        {
            this.Coord = new Collection<double>();
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [NotMappedAttribute()]
        [XmlAttributeAttribute("extraHeight")]
        public double ExtraHeightValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ExtraHeight-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ExtraHeight property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool ExtraHeightValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public System.Nullable<double> ExtraHeight
        {
            get
            {
                if (this.ExtraHeightValueSpecified)
                {
                    return this.ExtraHeightValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ExtraHeightValue = value.GetValueOrDefault();
                this.ExtraHeightValueSpecified = value.HasValue;
            }
        }
        
        [XmlAttributeAttribute("epsgCode")]
        public string EpsgCode { get; set; }
        
        [XmlAttributeAttribute("heightEpsgCode")]
        public string HeightEpsgCode { get; set; }
    }
}
