//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("tOcpPropService", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    internal partial class TOcpPropService
    {
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der diese Entität eindeutig identifiziert, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value uniquely identifying this entity.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [KeyAttribute()]
        public long Id { get; set; }
        
        [XmlIgnoreAttribute()]
        private bool _passenger = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("passenger")]
        public bool Passenger
        {
            get
            {
                return this._passenger;
            }
            set
            {
                this._passenger = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private bool _service = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("service")]
        public bool Service
        {
            get
            {
                return this._service;
            }
            set
            {
                this._service = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private bool _ship = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("ship")]
        public bool Ship
        {
            get
            {
                return this._ship;
            }
            set
            {
                this._ship = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private bool _bus = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("bus")]
        public bool Bus
        {
            get
            {
                return this._bus;
            }
            set
            {
                this._bus = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private bool _airport = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("airport")]
        public bool Airport
        {
            get
            {
                return this._airport;
            }
            set
            {
                this._airport = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private bool _tariffpoint = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("tariffpoint")]
        public bool Tariffpoint
        {
            get
            {
                return this._tariffpoint;
            }
            set
            {
                this._tariffpoint = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private bool _goodsLoading = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("goodsLoading")]
        public bool GoodsLoading
        {
            get
            {
                return this._goodsLoading;
            }
            set
            {
                this._goodsLoading = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private bool _goodsSiding = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("goodsSiding")]
        public bool GoodsSiding
        {
            get
            {
                return this._goodsSiding;
            }
            set
            {
                this._goodsSiding = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private bool _goodsIntermodal = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("goodsIntermodal")]
        public bool GoodsIntermodal
        {
            get
            {
                return this._goodsIntermodal;
            }
            set
            {
                this._goodsIntermodal = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private bool _goodsMarshalling = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("goodsMarshalling")]
        public bool GoodsMarshalling
        {
            get
            {
                return this._goodsMarshalling;
            }
            set
            {
                this._goodsMarshalling = value;
            }
        }
    }
}
