//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This C# code was generated by XmlSchemaClassGenerator version 1.0.0.0.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Models.XsdConvert.genericRailML
{
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("tTrain", Namespace="https://www.railml.org/schemas/2018")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlIncludeAttribute(typeof(genericRailML.ETrain))]
    internal partial class TTrain : genericRailML.TElementWithIDAndName, IATrain
    {
        
        [XmlAttributeAttribute("type")]
        public TTrainType Type { get; set; }
        
        [XmlAttributeAttribute("trainNumber")]
        public string TrainNumber { get; set; }
        
        [XmlAttributeAttribute("additionalTrainNumber")]
        public string AdditionalTrainNumber { get; set; }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [NotMappedAttribute()]
        [XmlAttributeAttribute("scope")]
        public TTrainScope ScopeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Scope-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Scope property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool ScopeValueSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        public System.Nullable<TTrainScope> Scope
        {
            get
            {
                if (this.ScopeValueSpecified)
                {
                    return this.ScopeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ScopeValue = value.GetValueOrDefault();
                this.ScopeValueSpecified = value.HasValue;
            }
        }
        
        [XmlAttributeAttribute("processStatus")]
        public string ProcessStatus { get; set; }
        
        /// <summary>
        /// <para>a free attribute for further descriptions</para>
        /// </summary>
        [XmlAttributeAttribute("remarks")]
        public string Remarks { get; set; }
        
        /// <summary>
        /// <para>indicates, that this train is no longer valid and should be canceled out of a previously delivered set</para>
        /// </summary>
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        [NotMappedAttribute()]
        [XmlAttributeAttribute("cancellation")]
        public bool CancellationValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Cancellation-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Cancellation property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        [NotMappedAttribute()]
        [EditorBrowsableAttribute(EditorBrowsableState.Never)]
        public bool CancellationValueSpecified { get; set; }
        
        /// <summary>
        /// <para>indicates, that this train is no longer valid and should be canceled out of a previously delivered set</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public System.Nullable<bool> Cancellation
        {
            get
            {
                if (this.CancellationValueSpecified)
                {
                    return this.CancellationValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CancellationValue = value.GetValueOrDefault();
                this.CancellationValueSpecified = value.HasValue;
            }
        }
    }
}
